name: "Energa meter (dev)"
description: "Energa meter addon"
version: "0.1.3"
slug: "energa_meter_dev"
init: false
options:
  energa_username: ""
  energa_password: ""
  log_level: "INFO"
schema:
  energa_username: str
  energa_password: password
  log_level: str
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000