name: "Energa meter"
description: "Energa meter addon"
version: "0.1.1"
slug: "energa_meter"
init: false
options:
  energa_username: ""
  energa_password: ""
schema:
  energa_username: str
  energa_password: password
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000